name: Build and Deploy

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set node version to 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      #   - name: Get pnpm store directory
      #     shell: bash
      #     run: |
      #         echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      #   - uses: actions/cache@v3
      #     name: Setup pnpm cache
      #     with:
      #       path: ${{ env.STORE_PATH }}
      #       key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      #       restore-keys: |
      #         ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm nx build ui

      - name: Share Artifact@v4
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken={{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: build

      - name: Display structure of downloaded files
        run: ls -R build

      - name: Deploy to npm
        run: npm publish --access=public
